### ISSUE TITLE
gilectomy fails to compile with clang

### ISSUE THREAD

**Issue by gpshead** [larryhastings/gilectomy#1]
The first one found in pydebug mode:

```
../gilectomy/Objects/methodobject.c:403:12: error: use of undeclared identifier 'counter'; did you mean 'count'?
    assert(counter == 0);
```

the first one found NOT in pydebug mode:

```
../gilectomy/Modules/gcmodule.c:1588:40: error: initializer element is not a compile-time constant
static furtex_t gc_furtex = { 0, 0, 0, "gc_lock" };
                                       ^~~~~~~~~
```

i expect there are other errors.  clang is your friend. :)

**Comment by larryhastings** [comment]
Bless you for trying! 
On May 28, 2016 5:24 PM, "Gregory P. Smith" notifications@github.com wrote:The first one found in pydebug mode:

../gilectomy/Objects/methodobject.c:403:12: error: use of undeclared identifier 'counter'; did you mean 'count'?
    assert(counter == 0);

the first one found NOT in pydebug mode:

../gilectomy/Modules/gcmodule.c:1588:40: error: initializer element is not a compile-time constant
static furtex_t gc_furtex = { 0, 0, 0, "gc_lock" };
                                       ^~~~~~~~~

i expect there are other errors.  clang is your friend. :)

**Comment by larryhastings** [comment]
I've fixed both these issues already.
