### ISSUE TITLE
Any comments on nogil?

### ISSUE THREAD

**Issue by bugsbugsbux** [larryhastings/gilectomy#51]
Does Sam Gross' [nogil](https://github.com/colesbury/nogil/) officially end the gilectomy?

**Comment by larryhastings** [comment]
If you like.  I'd use the verb "supersede", as in, it supersedes the Gilectomy.

Sam emailed me nearly a year ago about it, and already he was way farther along than I ever got the Gilectomy.  But he asked me to keep his work a secret until he was ready to reveal it himself.  Finally he's revealed his work, and I can go ahead and publicly declare the Gilectomy is abandoned.

**Comment by bugsbugsbux** [comment]
thanks for the statement. im glad that some dedicated people like you and sam gross continued working on this all those years and kept the communitys hope of a gil free future alive until it finally succeeded! this is very inspiring. i enjoyed your talks btw
